# A Docker image to be used to build your app
image: node:lts

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

stages:
  - pages

pages:
  stage: pages
  script:
    - npm i
    - npm run build --output=public
    - npm run postbuild

  artifacts:
    paths:
      # The folder that contains the built files to be published. This
      # must be called "public".
      - public
  
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH

